// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoadAccidentsAPI;

#nullable disable

namespace RoadAccidentsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250401065219_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("IncidentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFatal")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfCasualties")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfVehiclesInvolved")
                        .HasColumnType("integer");

                    b.Property<int>("lightConditions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Accidents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
